#!/usr/bin/env python3
"""Regenerate type stubs for the C++ extension.

Run this after touching anything in `ext/bind_*.cpp`. The output lands
in `src/witty_for_python/_witty_for_python/*.pyi` and `src/witty_for_python/py.typed`,
which are checked into the repo and ship inside the wheel.

The stubs are generated by nanobind's built-in stubgen; the recursive
flag walks the chart + Json submodules.

Usage:
    python scripts/regenerate_stubs.py

CI runs this script and fails if the output differs from what's
checked in.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
PKG_DIR = REPO / "src" / "witty_for_python"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Don't write — fail if the checked-in stubs differ "
             "from a fresh generation.")
    args = parser.parse_args()

    if args.check:
        # Generate to a temp dir; diff against the committed copy.
        import tempfile
        import filecmp
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            subprocess.run(
                [sys.executable, "-m", "nanobind.stubgen",
                 "-m", "witty_for_python._witty_for_python",
                 "-r",
                 "-O", str(tmp_path),
                 "-M", str(tmp_path / "py.typed"),
                 "-q"],
                check=True)
            # Compare every generated file to the checked-in version.
            mismatched: list[str] = []
            for gen in tmp_path.rglob("*"):
                if not gen.is_file():
                    continue
                rel = gen.relative_to(tmp_path)
                committed = PKG_DIR / rel
                if not committed.exists():
                    mismatched.append(f"missing: {rel}")
                elif not filecmp.cmp(gen, committed, shallow=False):
                    mismatched.append(f"out of date: {rel}")
            if mismatched:
                sys.stderr.write(
                    "Stubs are stale — regenerate with:\n"
                    "    python scripts/regenerate_stubs.py\n\n"
                    "Differences:\n")
                for m in mismatched:
                    sys.stderr.write(f"  - {m}\n")
                return 1
            print("Stubs are up to date.")
            return 0

    # Generation mode: write to the source tree.
    subprocess.run(
        [sys.executable, "-m", "nanobind.stubgen",
         "-m", "witty_for_python._witty_for_python",
         "-r",
         "-O", str(PKG_DIR),
         "-M", str(PKG_DIR / "py.typed")],
        check=True)
    print(f"Stubs written to {PKG_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
