#!/usr/bin/env python3
"""Regenerate type stubs for the C++ extension.

Run this after touching anything in `ext/bind_*.cpp`. The output lands
in `src/witty_for_python/_witty_for_python/*.pyi` and `src/witty_for_python/py.typed`,
which are checked into the repo and ship inside the wheel.

The stubs are generated by nanobind's built-in stubgen; the recursive
flag walks the chart + Json submodules. We then run a post-processing
pass that rewrites the fluent `(self, X: object) -> object` methods
(add_widget and friends — see docs/binding_design.md §4.2) to use a
TypeVar, so IDEs see `c.add_widget(btn).clicked` typed as `btn`'s
concrete type rather than `object`.

Usage:
    python scripts/regenerate_stubs.py

CI runs this script and fails if the output differs from what's
checked in.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
PKG_DIR = REPO / "src" / "witty_for_python"


# Match `(self, [prefix args,] NAME: object [, suffix args]) -> object: ...`.
# The fluent argument can be the first OR appear after other positional
# args (e.g. `bind_widget(self, var_name: str, widget: object) -> object`).
_FLUENT_SIG_RE = re.compile(
    r"def (?P<method>\w+)\(self"
    r"(?P<before>(?:, \w+: [^,)]+)*?)"
    r", (?P<argname>\w+): object"
    r"(?P<after>(?:, [^)]+)?)\) -> object:"
)

# Match `(self, [prefix args,] NAME: list [, suffix args]) -> list: ...` for
# the bulk variants (add_widgets / append_row / append_column / etc.) —
# same TypeVar rewrite logic but lifted to list[T] / list[T].
_FLUENT_LIST_SIG_RE = re.compile(
    r"def (?P<method>\w+)\(self"
    r"(?P<before>(?:, \w+: [^,)]+)*?)"
    r", (?P<argname>\w+): list"
    r"(?P<after>(?:, [^)]+)?)\) -> list:"
)


def _rewrite_fluent_typevars(stub_path: Path) -> None:
    """Rewrite `(self, x: object) -> object` to `(self, x: _T) -> _T`.

    `_T` is unbounded — nanobind's runtime check rejects anything that
    isn't a heap-allocated bound class on the first `nb::cast<unique_ptr>`
    line. The type-checker just needs to see "input type echoes back."
    Also handles the bulk `(self, xs: list) -> list` form, lifted to
    `list[_T] -> list[_T]`.
    """
    text = stub_path.read_text(encoding="utf-8")
    n_subs_single = len(_FLUENT_SIG_RE.findall(text))
    n_subs_list = len(_FLUENT_LIST_SIG_RE.findall(text))
    if n_subs_single + n_subs_list == 0:
        return

    text = _FLUENT_SIG_RE.sub(
        r"def \g<method>(self\g<before>, \g<argname>: _T\g<after>) -> _T:",
        text,
    )
    text = _FLUENT_LIST_SIG_RE.sub(
        r"def \g<method>(self\g<before>, \g<argname>: list[_T]\g<after>) -> list[_T]:",
        text,
    )

    # Inject `_T = TypeVar("_T")` after the existing `from typing import …`
    # (or near the top if there's no typing import). Idempotent — bail if
    # we've already injected.
    if "_T = TypeVar" in text:
        return

    typevar_decl = '_T = TypeVar("_T")\n'
    typing_import = re.search(
        r"^from typing import \(?([^()\n]+(?:\n[^()\n]+)*)\)?$",
        text, re.MULTILINE,
    )
    if typing_import:
        # Append TypeVar to the existing import if not present, then
        # add the declaration after the import block.
        if "TypeVar" not in typing_import.group(1):
            text = (
                text[:typing_import.start()]
                + "from typing import TypeVar, " + typing_import.group(1).lstrip()
                + text[typing_import.end():]
            )
        else:
            # TypeVar already imported — leave the import line alone.
            pass
        # Insert the _T decl after the import block.
        m = re.search(r"^from typing import .*?$", text, re.MULTILINE)
        assert m is not None
        text = text[:m.end()] + "\n\n" + typevar_decl + text[m.end():]
    else:
        # No typing import — add one near the top, after any module docstring
        # or existing imports.
        text = (
            "from typing import TypeVar\n\n"
            + typevar_decl + "\n"
            + text
        )

    stub_path.write_text(text, encoding="utf-8")


def _post_process(out_dir: Path) -> None:
    """Apply the TypeVar rewrite to every generated .pyi under out_dir."""
    for stub in out_dir.rglob("*.pyi"):
        _rewrite_fluent_typevars(stub)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Don't write — fail if the checked-in stubs differ "
             "from a fresh generation.")
    args = parser.parse_args()

    if args.check:
        # Generate to a temp dir; diff against the committed copy.
        import tempfile
        import filecmp
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            subprocess.run(
                [sys.executable, "-m", "nanobind.stubgen",
                 "-m", "witty_for_python._witty_for_python",
                 "-r",
                 "-O", str(tmp_path),
                 "-M", str(tmp_path / "py.typed"),
                 "-q"],
                check=True)
            _post_process(tmp_path)
            # Compare every generated file to the checked-in version.
            mismatched: list[str] = []
            for gen in tmp_path.rglob("*"):
                if not gen.is_file():
                    continue
                rel = gen.relative_to(tmp_path)
                committed = PKG_DIR / rel
                if not committed.exists():
                    mismatched.append(f"missing: {rel}")
                elif not filecmp.cmp(gen, committed, shallow=False):
                    mismatched.append(f"out of date: {rel}")
            if mismatched:
                sys.stderr.write(
                    "Stubs are stale — regenerate with:\n"
                    "    python scripts/regenerate_stubs.py\n\n"
                    "Differences:\n")
                for m in mismatched:
                    sys.stderr.write(f"  - {m}\n")
                return 1
            print("Stubs are up to date.")
            return 0

    # Generation mode: write to the source tree.
    subprocess.run(
        [sys.executable, "-m", "nanobind.stubgen",
         "-m", "witty_for_python._witty_for_python",
         "-r",
         "-O", str(PKG_DIR),
         "-M", str(PKG_DIR / "py.typed")],
        check=True)
    _post_process(PKG_DIR)
    print(f"Stubs written to {PKG_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
